[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript']

# インサートモードに入ったら読み込む
#[[plugins]]
#repo = 'Shougo/neocomplete.vim'
#on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Yggdroot/indentLine'
on_i = 1


[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-clang'
hook_source = '''
  let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.8/lib/libclang-3.8.so.1'
  let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''
on_ft = ['c','cpp','cmake']
depends = ['deoplete.nvim']

#[[plugins]]
#repo = 'poppyschmo/deoplete-latex'
#on_ft = ['tex']
#depends = ['deoplete.nvim']

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
hook_source = '''
  let g:cpp_class_scope_highlight = 1
  let g:cpp_member_variable_highlight = 1
  let g:cpp_class_decl_highlight = 1
  let g:cpp_experimental_simple_template_highlight = 1
  let g:cpp_experimental_template_highlight = 1
  let g:cpp_concepts_highlight = 1
  let g:cpp_no_function_highlight = 1
'''
on_ft = ['cpp']

[[plugins]]
repo   = 'Shougo/unite.vim'

# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

# 特定のコマンドを打ったら読み込む
[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']

# 特定のマッピングを使ったら読み込む
# 又、gvim でしか利用しない
[[plugins]]
repo   = 'thinca/vim-fontzoom'
on_cmd = ['Fontzoom']
on_map = ['<Plug>(fontzoom-']
gui    = 1

[[plugins]]
repo   = 'lervag/vimtex'
hook_source = '''
  let g:vimtex_compiler_latexmk = {
      \   'background' : 1,
      \   'build_dir' : '',
      \   'callback' : 1,
      \   'continuous' : 1,
      \   'options' : [
      \     '-f',
      \     '-pdfdvi',
      \     '-verbose',
      \     '-file-line-error',
      \     '-synctex=1',
      \     '-interaction=nonstopmode',
      \   ],
      \ }
  let g:vimtex_view_general_viewer = 'qpdfview'
  let g:vimtex_compiler_progname = 'nvr'
'''
on_ft = ['tex']

