# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

#[[plugins]] # カラースキーマ
#repo = 'jacoborus/tender.vim'
#hook_add = '''
#  colorscheme tender
#'''

#[[plugins]] # カラースキーマ
#repo = 'Haron-Prime/Antares'
#hook_add = '''
#  colorscheme antares
#'''

#[[plugins]] # カラースキーマ
#repo = 'altercation/vim-colors-solarized'
#hook_add = '''
#  colorscheme solarized
#'''

#[[plugins]] # カラースキーマ
#repo = 'romainl/Apprentice'
#hook_add = '''
#  colorscheme apprentice
#'''

[[plugins]] # カラースキーマ
repo = 'tomasr/molokai'
hook_add = '''
  colorscheme molokai
'''

# ブランチやタグを指定したいとき
[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

# 特定の条件で読み込みたいとき
[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Townk/Vim-autoclose'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'


